language: go
go_import_path: go-hep.org/x/exp
os:
  - linux

env:
 - TAGS="-tags travis"

matrix:
 fast_finish: true
 allow_failures:
   - go: master
 include:
   - go: 1.12.x
     env:
       - TAGS="-tags travis"
       - COVERAGE="-cover"
   - go: 1.11.x
     env:
       - TAGS="-tags travis"
   - go: 1.10.x
     env:
       - TAGS="-tags travis"
   - go: master
     env:
       - TAGS="-tags travis"

sudo: required

notifications:
  email:
    recipients:
      - go.hep.dev@gmail.com
    on_success: always
    on_failure: always

before_script:
 - sudo apt-get install -qq pkg-config fuse
 - sudo modprobe fuse
 - sudo chmod 666 /dev/fuse
 - sudo chown root:$USER /etc/fuse.conf

script:
 - go get -d -t -v ./...
 - go install -v $TAGS ./...
 - go run ./ci/run-tests.go -race $TAGS $COVERAGE

after_success:
 - bash <(curl -s https://codecov.io/bash)
