language: go
go_import_path: go-hep.org/x/exp
os:
  - linux

env:
 - TAGS="-tags travis"

matrix:
 fast_finish: true
 allow_failures:
   - go: master
 include:
   - go: 1.14.x
     env:
       - TAGS="-tags travis"
   - go: 1.13.x
     env:
       - TAGS="-tags travis"
   - go: master
     env:
       - TAGS="-tags travis"

sudo: required

before_script:
 - sudo apt-get install -qq pkg-config fuse libgles2-mesa-dev libxkbcommon-dev libxkbcommon-x11-dev
 - sudo modprobe fuse
 - sudo chmod 666 /dev/fuse
 - sudo chown root:$USER /etc/fuse.conf

script:
 - go get -d -t -v ./...
 - GOARCH=386   go install -v $TAGS ./...
 - GOARCH=amd64 go install -v $TAGS ./...
 - go run ./ci/run-tests.go -race $TAGS $COVERAGE
